### ISSUE TITLE
Discord Music Player v6.0.0 Update

### ISSUE THREAD

**Issue by SushiBtw** [SushiBtw/discord-music-player#13]
## Discord Music Player v6.0.0 Update
I am starting to work on the v6.0.0 Uptate, with **[v6.0.0 branch](/SushiBtw/discord-music-player/tree/v6.0.0)**.

**What I am planning to add?:**
- [x] **YouTube Link Support** (the current one is a bit buggy per #12),
- [x] **YouTube Filters** such as ``TIME: short/long; UPLOADED: today/week/month/year; SORTBY: rating/views/date`` (per #3),
- [x] **Shuffle Method**, to play queue songs in shuffle (per #3),
- [x] **Progress Bar**, of the current song (suggested in #5),
- [x] Code quality fixes,
- [x] Code size reduction,
- [x] README.md Rewrite,
- [x] Minor Fixes.

### Note, that this branch is experimental and can cause such errors.
*Please report every bug in the **[Issues Tab](/SushiBtw/discord-music-player/issues)**, when everything would be ready, **v6.0.0** would be officially published as [NPM Module](https://www.npmjs.com/package/discord-music-player).*

### Any suggestions?
 Please use the **[Issues](/SushiBtw/discord-music-player/issues)** or **[Pull Requests](/SushiBtw/discord-music-player/pulls)** Tab.

**Comment by SushiBtw** [comment]
### Code Updates
- **[27.11]** Added **YouTube Link Support** in https://github.com/SushiBtw/discord-music-player/commit/04cd900054ff8ab1740ae32bacd9eab5c4e668a9

*Ready to test.*
