### ISSUE TITLE
Discord.js v13 Voice Update - Discord Music Player v8 is out!

### ISSUE THREAD

**Issue by SushiBtw** [SushiBtw/discord-music-player#177]
Hey everyone 👋
I am currently working on a dev v8.0.0 build for Discord.js v13, I will release it as soon as it will be more stable and I will fix all errors. It should came up soon but only as a dev build, so you will need to update manually to the specific version.

Let me know if you have any questions, feel free to comment bellow 💬

Thanks,
DPM Creator
~Sushi

**Comment by SushiBtw** [comment]
**Hey everyone! I've been working on the Discord.js v13 (DMP v8.0.0@dev) build for few days now!**
I managed to get it working as soon as possible, with less functions for now, but every function bound in should work for now.

You can download the package via NPM:
```sh
npm i discord-music-player@dev
```

The docs can be found [here](https://github.com/SushiBtw/discord-music-player/tree/development#readme) - but I am still working on them!
Every function from v7 should be on the dev build in few days.

Thanks for your time,
I hope you enjoy DiscordJS V13 😋

**Comment by SushiBtw** [comment]
Hey everyone, DMP `8.0.0-dev7` is out!

Here what we've got for now:
- [x] Added `Queue#playlist`,
- [x] Added link support for `Utils#search` (`Queue#play` & `Queue#playlist`),
- [x] Fixed `[BUG] InvalidPlaylist when its Valid URL` (#176),
- [x] Added support for `PlayerOptions#localAddress`, `PlayOptions#localAdress`, `PlaylistOptions#localAdress`,
- [ ] [FR] New docs (#156),
- [ ] [FR] progressBar positioning (#141),
- [ ] [FR] Youtube Timecodes support (#140),
- [ ] [FR] Fetch more than 100 songs in YT playlists (#122).

All FR's above will be added tomorrow, hope so!

Install latest dev version:
```sh
npm i discord-music-player@dev
```

Thanks,
Sushi.
